#!/usr/bin/env python3
#
# Builds a report-aware context document for the GitHub report-driven coding
# agent by combining:
#   1. a repository context snapshot (generated by scan_dreamengin_context.py)
#   2. a report from a repo file or free-form text (workflow input / issue body)
#
# Usage:
#   python .github/scripts/assemble_report_context.py \
#     --repo-context .github/generated/dreamengin-context.md \
#     --report-path docs/BUGS.md \
#     --out .github/generated/report-agent-context.md
#
# Or:
#   REPORT_TEXT="..." python .github/scripts/assemble_report_context.py \
#     --repo-context .github/generated/dreamengin-context.md \
#     --out .github/generated/report-agent-context.md

import argparse
import os
import sys


def read_text(path: str) -> str:
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as fh:
            return fh.read()
    except FileNotFoundError:
        return ""


def main() -> None:
    parser = argparse.ArgumentParser(description="Build report-aware context for the GitHub coding agent")
    parser.add_argument("--repo-context", required=True, help="Path to dreamengin-context.md")
    parser.add_argument("--report-path", help="Path to a markdown/json report inside the repo")
    parser.add_argument("--game-catalog-path", help="Path to generated game catalog markdown/json")
    parser.add_argument("--advanced-targets-path", help="Path to advanced game target manifest JSON")
    parser.add_argument("--report-source", default="", help="Human-readable label for the report source")
    parser.add_argument("--out", required=True, help="Path to write the combined context markdown")
    args = parser.parse_args()

    repo_context = read_text(args.repo_context).strip()
    if not repo_context:
        print(f"Error: repo context not found at {args.repo_context}", file=sys.stderr)
        sys.exit(1)

    env_report_text = os.environ.get("REPORT_TEXT", "").strip()
    file_report_text = read_text(args.report_path).strip() if args.report_path else ""
    report_text = env_report_text or file_report_text
    game_catalog_text = read_text(args.game_catalog_path).strip() if args.game_catalog_path else ""
    advanced_targets_text = read_text(args.advanced_targets_path).strip() if args.advanced_targets_path else ""

    if not report_text:
        print(
            "Error: no report content was provided. Supply --report-path or REPORT_TEXT.",
            file=sys.stderr,
        )
        sys.exit(1)

    report_source = args.report_source.strip()
    if not report_source:
        if env_report_text:
            report_source = "workflow / issue text"
        elif args.report_path:
            report_source = args.report_path
        else:
            report_source = "unknown"

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("# DREAMengin Report-Agent Context\n\n")
        fh.write("## Report Source\n\n")
        fh.write(f"- {report_source}\n\n")
        fh.write("## Report\n\n")
        fh.write("<report>\n")
        fh.write(report_text)
        if not report_text.endswith("\n"):
            fh.write("\n")
        fh.write("</report>\n\n")
        if advanced_targets_text:
            fh.write("## Advanced Game Targets\n\n")
            fh.write("<advanced_game_targets>\n")
            fh.write(advanced_targets_text)
            if not advanced_targets_text.endswith("\n"):
                fh.write("\n")
            fh.write("</advanced_game_targets>\n\n")
        if game_catalog_text:
            fh.write("## Game Catalog\n\n")
            fh.write("<game_catalog>\n")
            fh.write(game_catalog_text)
            if not game_catalog_text.endswith("\n"):
                fh.write("\n")
            fh.write("</game_catalog>\n\n")
        fh.write("## Repository Context\n\n")
        fh.write("<repo_context>\n")
        fh.write(repo_context)
        if not repo_context.endswith("\n"):
            fh.write("\n")
        fh.write("</repo_context>\n")

    print(f"Report-agent context written to {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
