// scripts/prepare.mjs
// One script to stop the pain. Run before build.
// - Forces dynamic on known server pages (avoids export/prerender errors)
// - Generates modules/registry.generated.(ts|js)
// - Writes a stable shim consumed by pages: lib/modules/registry.gen.(ts|js)

import { readdir, readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const APP = path.join(ROOT, 'app');
const MOD = path.join(ROOT, 'modules');
const WIDGETS = path.join(MOD, 'widgets');
const CONNECTORS = path.join(MOD, 'connectors');

const modeJS = process.argv.includes('--js'); // optional: generate .js instead of .ts
const REG_OUT = path.join(MOD, `registry.generated.${modeJS ? 'js' : 'ts'}`);
const SHIM_OUT = path.join(ROOT, 'lib', 'modules', `registry.gen.${modeJS ? 'js' : 'ts'}`);

async function exists(p) { try { await stat(p); return true; } catch { return false; } }
async function ensureDir(p) { await mkdir(p, { recursive: true }); }

function posixRel(from, to) {
  return path.posix.join(path.relative(from, to).replace(/\\/g, '/'));
}

async function forceDynamic(file) {
  if (!(await exists(file))) return;
  let src = await readFile(file, 'utf8');
  if (!/export\s+const\s+dynamic\s*=/.test(src)) {
    src = `export const dynamic = 'force-dynamic';\n` + src;
    await writeFile(file, src, 'utf8');
    console.log('[prepare] dynamic ->', path.relative(ROOT, file));
  }
}

async function scanModules(dir) {
  const found = [];
  if (!(await exists(dir))) return found;
  const entries = await readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    if (e.isDirectory()) {
      const base = e.name;
      const d = path.join(dir, base);
      const hasIndex =
        (await exists(path.join(d, 'index.ts'))) ||
        (await exists(path.join(d, 'index.tsx'))) ||
        (await exists(path.join(d, 'index.js'))) ||
        (await exists(path.join(d, 'index.jsx')));
      if (hasIndex) {
        found.push({ key: e.name, rel: posixRel(MOD, d) });
      }
    } else if (/\.(t|j)sx?$/.test(e.name)) {
      const base = e.name.replace(/\.(t|j)sx?$/, '');
      if (base !== 'index') {
        found.push({ key: base, rel: posixRel(MOD, path.join(dir, base)) });
      }
    }
  }
  // de-dupe + sort
  const seen = new Set();
  return found.filter(f => !seen.has(f.key) && seen.add(f.key))
              .sort((a,b)=>a.key.localeCompare(b.key));
}

async function writeRegistry(widgets, connectors) {
  const header = `// AUTO-GENERATED by scripts/prepare.mjs. Do not edit.
`;
  const body =
`${modeJS ? '' : 'export '}const widgetRegistry = {
${widgets.map(m => `  "${m.key}": () => import("./${m.rel}")`).join(',\n')}
};

${modeJS ? '' : 'export '}const connectorRegistry = {
${connectors.map(m => `  "${m.key}": () => import("./${m.rel}")`).join(',\n')}
};

${modeJS
  ? `export { widgetRegistry, connectorRegistry };`
  : `export { widgetRegistry, connectorRegistry };
export type WidgetKey = keyof typeof widgetRegistry;
export type ConnectorKey = keyof typeof connectorRegistry;`
}
`;
  await ensureDir(MOD);
  await writeFile(REG_OUT, header + body, 'utf8');
  console.log('[prepare] registry ->', path.relative(ROOT, REG_OUT), `(${widgets.length} widgets, ${connectors.length} connectors)`);
}

async function writeShim() {
  const importPath = './' + posixRel(path.dirname(SHIM_OUT), REG_OUT).replace(/^(\.\/)+/, '');
  const header = `// GENERATED shim. Safe shape for pages to consume.
import { widgetRegistry, connectorRegistry } from '${importPath}';
`;
  const body =
`${modeJS ? '' : 'export '}const widgetModules = Object.entries(widgetRegistry).map(([slug, load]) => ({
  slug,
  name: slug,
  load,
  Component: undefined
}));

${modeJS ? '' : 'export '}const connectorModules = Object.entries(connectorRegistry).map(([slug, load]) => ({
  slug,
  name: slug,
  load,
  ingest: undefined
}));

${modeJS
  ? `export { widgetModules, connectorModules };`
  : `export { widgetModules, connectorModules };
export type WidgetEntry = { slug: string; name: string; load: () => Promise<any>; Component?: any };
export type ConnectorEntry = { slug: string; name: string; load: () => Promise<any>; ingest?: (args:any)=>Promise<any> };`
}
`;
  await ensureDir(path.dirname(SHIM_OUT));
  await writeFile(SHIM_OUT, header + body, 'utf8');
  console.log('[prepare] shim ->', path.relative(ROOT, SHIM_OUT));
}

async function main() {
  // 1) Force dynamic on pages that previously failed export
  const candidates = [
    path.join(APP, 'ads', 'page.tsx'),
    path.join(APP, 'connectors', 'page.tsx'),
    path.join(APP, 'home', 'page.tsx'),
    path.join(APP, 'music', 'page.tsx'),
    path.join(APP, 'shop', 'page.tsx'),
    path.join(APP, 'shop', 'me', 'page.tsx'),
    path.join(APP, 'page.tsx'),
    path.join(APP, '(marketing)', 'page.tsx'),
  ];
  for (const f of candidates) await forceDynamic(f);

  // 2) Generate registry
  await ensureDir(MOD);
  await ensureDir(WIDGETS);
  await ensureDir(CONNECTORS);
  const widgets = await scanModules(WIDGETS);
  const connectors = await scanModules(CONNECTORS);
  await writeRegistry(widgets, connectors);

  // 3) Shim
  await writeShim();

  console.log('[prepare] done');
}

main().catch((e)=>{ console.error(e); process.exit(0); });
